version: '3.2'

services:
  database:
    image: crunchydata/crunchy-postgres:centos8-13.4-4.7.2
    container_name: {{cookiecutter.project_name}}_database
    ports:
      - "5432:5432"
    environment:
      - MODE=postgres
      - PG_MODE=primary
      - PG_USER=postgres
      - PG_PASSWORD=abc
      - PG_DATABASE={{cookiecutter.project_name}}
      - PG_PRIMARY_USER=repluser
      - PG_PRIMARY_PASSWORD=abc
      - PG_ROOT_PASSWORD=abc
      - PG_PRIMARY_PORT=5432

  app:
    image: {{cookiecutter.project_repo}}
    build:
      context: .
      args:
        CONTAINER_REGISTRY: ${CONTAINER_REGISTRY}
        PIP_ACCESS_TOKEN: ${PIP_ACCESS_TOKEN}
    container_name: {{cookiecutter.project_name}}_app
    environment:
      - PG_PASSWORD=abc
      - PG_USER=postgres
      - PG_DBNAME={{cookiecutter.project_name}}
      - PG_PORT=5432
      - PG_HOST=database
      - AD_TENANT_ID=${AD_TENANT_ID}
      - AD_CLIENT_ID=${AD_CLIENT_ID}
      - AD_CLIENT_SECRET=${AD_CLIENT_SECRET}
      - AD_REDIRECT_URL=http://localhost:6543/authorized
      - ACCOUNTS_TOKEN_SECRET=mysecret
    depends_on: 
      - "database"
    ports:
      - "6543:6543"
      - "8888:8888"
    tty: true
