name: CICD - ACR - Python

on:
  schedule:
    - cron: "0 0 * * SUN"
  push:
    branches:
      - "**"
    tags:
      - "v*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cicd_acr:
    uses: VanOord/datalab-github-actions/.github/workflows/cicd-acr-python.yml@master
    with:
      tag: {{cookiecutter.project_repo}}
      namespace: {{cookiecutter.project_name}}
    secrets: inherit